# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gaBfIvcdDJ76gWKZx9phiM40RihPB2je
"""

import pandas as pd
import matplotlib.pyplot as plt

# 1. Dados Brutos da Loja (Simulando o que o cliente te daria)
dados = {
    'Produto': ['Teclado Mecânico', 'Mouse Gamer', 'Monitor 144Hz', 'Cabo HDMI', 'Headset'],
    'Preco_Venda': [350.00, 150.00, 1200.00, 45.00, 280.00],
    'Custo_Unitario': [180.00, 90.00, 950.00, 10.00, 210.00],
    'Qtd_Vendida': [45, 80, 12, 150, 20]
}

df = pd.DataFrame(dados)

# 2. Cálculos de Inteligência Financeira
df['Lucro_Unitario'] = df['Preco_Venda'] - df['Custo_Unitario']
df['Lucro_Total'] = df['Lucro_Unitario'] * df['Qtd_Vendida']
df['Margem_%'] = (df['Lucro_Unitario'] / df['Preco_Venda']) * 100

# 3. Gerando o Gráfico de Lucro Total por Produto
plt.figure(figsize=(10, 6))
# Cores: verde para alta margem, vermelho para baixa
cores = ['green' if x > 30 else 'orange' for x in df['Margem_%']]

plt.bar(df['Produto'], df['Lucro_Total'], color=cores)

plt.title('Lucro Total Gerado por Produto (R$)', fontsize=14)
plt.ylabel('Lucro Acumulado (R$)', fontsize=12)
plt.xticks(rotation=45)
plt.grid(axis='y', linestyle='--', alpha=0.3)

# Adicionando os rótulos de lucro nas barras
for i, v in enumerate(df['Lucro_Total']):
    plt.text(i, v + 50, f'R$ {v:,.0f}', ha='center', fontweight='bold')

plt.tight_layout()
plt.show()